# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılım ile ilgili herşey/Çeviri programı/ceviri_programi.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 649)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/1492608019-18-google-translate-text-language-translation_83386.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_ceviri = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ceviri.setGeometry(QtCore.QRect(250, 240, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ceviri.setFont(font)
        self.pushButton_ceviri.setIcon(icon)
        self.pushButton_ceviri.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_ceviri.setObjectName("pushButton_ceviri")
        self.pushButton_ceviriKaydet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ceviriKaydet.setGeometry(QtCore.QRect(390, 500, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_ceviriKaydet.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/discet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ceviriKaydet.setIcon(icon1)
        self.pushButton_ceviriKaydet.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_ceviriKaydet.setObjectName("pushButton_ceviriKaydet")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 200, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_word = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_word.setGeometry(QtCore.QRect(10, 530, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_word.setFont(font)
        self.pushButton_word.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/1486565572-microsoft-office-word_81551.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_word.setIcon(icon2)
        self.pushButton_word.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_word.setObjectName("pushButton_word")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(0, 580, 211, 48))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.textEdit_source = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_source.setGeometry(QtCore.QRect(10, 10, 621, 181))
        self.textEdit_source.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_source.setFont(font)
        self.textEdit_source.setObjectName("textEdit_source")
        self.textEdit_target = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_target.setGeometry(QtCore.QRect(10, 290, 621, 201))
        self.textEdit_target.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit_target.setFont(font)
        self.textEdit_target.setObjectName("textEdit_target")
        self.comboBox_s = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_s.setGeometry(QtCore.QRect(10, 240, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_s.setFont(font)
        self.comboBox_s.setObjectName("comboBox_s")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_s.addItem("")
        self.comboBox_t = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_t.setGeometry(QtCore.QRect(410, 240, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_t.setFont(font)
        self.comboBox_t.setObjectName("comboBox_t")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.comboBox_t.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 490, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_excel_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excel_save.setGeometry(QtCore.QRect(70, 530, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_excel_save.setFont(font)
        self.pushButton_excel_save.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/Icons8-Ios7-Logos-Excel-Copyrighted.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_excel_save.setIcon(icon3)
        self.pushButton_excel_save.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_excel_save.setObjectName("pushButton_excel_save")
        self.pushButton_notepad_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_notepad_save.setGeometry(QtCore.QRect(130, 530, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_notepad_save.setFont(font)
        self.pushButton_notepad_save.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/Tatice-Cristal-Intense-Notepad-Bloc-notes.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_notepad_save.setIcon(icon4)
        self.pushButton_notepad_save.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_notepad_save.setObjectName("pushButton_notepad_save")
        self.pushButton_mail_send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mail_send.setGeometry(QtCore.QRect(320, 570, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_mail_send.setFont(font)
        self.pushButton_mail_send.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico/Graphicloads-100-Flat-2-Email.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_mail_send.setIcon(icon5)
        self.pushButton_mail_send.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_mail_send.setObjectName("pushButton_mail_send")
        self.pushButton_orijinalKaydet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_orijinalKaydet.setGeometry(QtCore.QRect(390, 560, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_orijinalKaydet.setFont(font)
        self.pushButton_orijinalKaydet.setIcon(icon1)
        self.pushButton_orijinalKaydet.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_orijinalKaydet.setObjectName("pushButton_orijinalKaydet")
        self.textEdit_mail = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_mail.setGeometry(QtCore.QRect(210, 530, 161, 31))
        self.textEdit_mail.setObjectName("textEdit_mail")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_ceviri.setText(_translate("MainWindow", "Translate"))
        self.pushButton_ceviriKaydet.setText(_translate("MainWindow", "Save translation as sound"))
        self.label.setText(_translate("MainWindow", "Source language"))
        self.label_2.setText(_translate("MainWindow", "Target language"))
        self.commandLinkButton.setText(_translate("MainWindow", "batuhanokmen.com"))
        self.comboBox_s.setCurrentText(_translate("MainWindow", "choose language"))
        self.comboBox_s.setItemText(0, _translate("MainWindow", "choose language"))
        self.comboBox_s.setItemText(1, _translate("MainWindow", "Türkçe"))
        self.comboBox_s.setItemText(2, _translate("MainWindow", "English"))
        self.comboBox_s.setItemText(3, _translate("MainWindow", "Español"))
        self.comboBox_s.setItemText(4, _translate("MainWindow", "Deutsch"))
        self.comboBox_s.setItemText(5, _translate("MainWindow", "Português"))
        self.comboBox_s.setItemText(6, _translate("MainWindow", "Polski"))
        self.comboBox_s.setItemText(7, _translate("MainWindow", "Italiano"))
        self.comboBox_s.setItemText(8, _translate("MainWindow", "Hrvatski"))
        self.comboBox_s.setItemText(9, _translate("MainWindow", "Nederlands"))
        self.comboBox_s.setItemText(10, _translate("MainWindow", "Dansk"))
        self.comboBox_s.setItemText(11, _translate("MainWindow", "Lietuvių"))
        self.comboBox_s.setItemText(12, _translate("MainWindow", "Eesti"))
        self.comboBox_s.setItemText(13, _translate("MainWindow", "Français"))
        self.comboBox_s.setItemText(14, _translate("MainWindow", "Arabic (United Arab Emirates)"))
        self.comboBox_s.setItemText(15, _translate("MainWindow", "Japanese (Japan)"))
        self.comboBox_s.setItemText(16, _translate("MainWindow", "Korean (South Korea)"))
        self.comboBox_s.setItemText(17, _translate("MainWindow", "Russian (Russia)"))
        self.comboBox_s.setItemText(18, _translate("MainWindow", "Chinese, Mandarin (Simplified, China)"))
        self.comboBox_s.setItemText(19, _translate("MainWindow", "Bulgarian"))
        self.comboBox_s.setItemText(20, _translate("MainWindow", "Czech"))
        self.comboBox_s.setItemText(21, _translate("MainWindow", "Danish"))
        self.comboBox_s.setItemText(22, _translate("MainWindow", "Greek"))
        self.comboBox_s.setItemText(23, _translate("MainWindow", "Finnish"))
        self.comboBox_s.setItemText(24, _translate("MainWindow", "Hebrew (Israel)"))
        self.comboBox_s.setItemText(25, _translate("MainWindow", "Hindi (India)"))
        self.comboBox_s.setItemText(26, _translate("MainWindow", "Croatian"))
        self.comboBox_s.setItemText(27, _translate("MainWindow", "Indonesian"))
        self.comboBox_s.setItemText(28, _translate("MainWindow", "Romanian"))
        self.comboBox_s.setItemText(29, _translate("MainWindow", "Serbian"))
        self.comboBox_s.setItemText(30, _translate("MainWindow", "Swedish"))
        self.comboBox_s.setItemText(31, _translate("MainWindow", "Ukrainian"))
        self.comboBox_s.setItemText(32, _translate("MainWindow", "Vietnamese"))
        self.comboBox_s.setItemText(33, _translate("MainWindow", "Afrikaans (South Africa)"))
        self.comboBox_s.setItemText(34, _translate("MainWindow", "Azerbaijani "))
        self.comboBox_s.setItemText(35, _translate("MainWindow", "Persian"))
        self.comboBox_s.setItemText(36, _translate("MainWindow", "Filipino"))
        self.comboBox_s.setItemText(37, _translate("MainWindow", "Swahili (Kenya)"))
        self.comboBox_s.setItemText(38, _translate("MainWindow", "Arabic (Saudi Arabia)"))
        self.comboBox_s.setItemText(39, _translate("MainWindow", "Arabic (Qatar)"))
        self.comboBox_s.setItemText(40, _translate("MainWindow", "Arabic (Kuwait)"))
        self.comboBox_t.setCurrentText(_translate("MainWindow", "choose language"))
        self.comboBox_t.setItemText(0, _translate("MainWindow", "choose language"))
        self.comboBox_t.setItemText(1, _translate("MainWindow", "Türkçe"))
        self.comboBox_t.setItemText(2, _translate("MainWindow", "English"))
        self.comboBox_t.setItemText(3, _translate("MainWindow", "Español"))
        self.comboBox_t.setItemText(4, _translate("MainWindow", "Deutsch"))
        self.comboBox_t.setItemText(5, _translate("MainWindow", "Português"))
        self.comboBox_t.setItemText(6, _translate("MainWindow", "Polski"))
        self.comboBox_t.setItemText(7, _translate("MainWindow", "Italiano"))
        self.comboBox_t.setItemText(8, _translate("MainWindow", "Hrvatski"))
        self.comboBox_t.setItemText(9, _translate("MainWindow", "Nederlands"))
        self.comboBox_t.setItemText(10, _translate("MainWindow", "Dansk"))
        self.comboBox_t.setItemText(11, _translate("MainWindow", "Lietuvių"))
        self.comboBox_t.setItemText(12, _translate("MainWindow", "Eesti"))
        self.comboBox_t.setItemText(13, _translate("MainWindow", "Français"))
        self.comboBox_t.setItemText(14, _translate("MainWindow", "Arabic (United Arab Emirates)"))
        self.comboBox_t.setItemText(15, _translate("MainWindow", "Japanese (Japan)"))
        self.comboBox_t.setItemText(16, _translate("MainWindow", "Korean (South Korea)"))
        self.comboBox_t.setItemText(17, _translate("MainWindow", "Russian (Russia)"))
        self.comboBox_t.setItemText(18, _translate("MainWindow", "Chinese, Mandarin (Simplified, China)"))
        self.comboBox_t.setItemText(19, _translate("MainWindow", "Bulgarian"))
        self.comboBox_t.setItemText(20, _translate("MainWindow", "Czech"))
        self.comboBox_t.setItemText(21, _translate("MainWindow", "Danish"))
        self.comboBox_t.setItemText(22, _translate("MainWindow", "Greek"))
        self.comboBox_t.setItemText(23, _translate("MainWindow", "Finnish"))
        self.comboBox_t.setItemText(24, _translate("MainWindow", "Hebrew (Israel)"))
        self.comboBox_t.setItemText(25, _translate("MainWindow", "Hindi (India)"))
        self.comboBox_t.setItemText(26, _translate("MainWindow", "Croatian"))
        self.comboBox_t.setItemText(27, _translate("MainWindow", "Indonesian"))
        self.comboBox_t.setItemText(28, _translate("MainWindow", "Romanian"))
        self.comboBox_t.setItemText(29, _translate("MainWindow", "Serbian"))
        self.comboBox_t.setItemText(30, _translate("MainWindow", "Swedish"))
        self.comboBox_t.setItemText(31, _translate("MainWindow", "Ukrainian"))
        self.comboBox_t.setItemText(32, _translate("MainWindow", "Vietnamese"))
        self.comboBox_t.setItemText(33, _translate("MainWindow", "Afrikaans (South Africa)"))
        self.comboBox_t.setItemText(34, _translate("MainWindow", "Azerbaijani "))
        self.comboBox_t.setItemText(35, _translate("MainWindow", "Persian"))
        self.comboBox_t.setItemText(36, _translate("MainWindow", "Filipino"))
        self.comboBox_t.setItemText(37, _translate("MainWindow", "Swahili (Kenya)"))
        self.comboBox_t.setItemText(38, _translate("MainWindow", "Arabic (Saudi Arabia)"))
        self.comboBox_t.setItemText(39, _translate("MainWindow", "Arabic (Qatar)"))
        self.comboBox_t.setItemText(40, _translate("MainWindow", "Arabic (Kuwait)"))
        self.label_3.setText(_translate("MainWindow", "Save as"))
        self.pushButton_orijinalKaydet.setText(_translate("MainWindow", "Save orijinal sound"))
        self.label_4.setText(_translate("MainWindow", "Send mail"))

import iconss_rc_rc
